name: Docker

on:
  workflow_call:
  
jobs:

  Docker:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
          
