name: Entrega continua

on:
  workflow_call:
  
jobs:

  Deploy_ECS:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Obtendo arquivo da tarefa
      run:
        |
        aws ecs describe-task-definition \
         --task-definition Tarefa_API-Go \
         --query taskDefinition > task-definition.json
