name: Entrega continua

on:
  workflow_call:
  
jobs:

  Deploy_ECS:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Donwload task definition
      run:
        |
        aws ecs describe-task-definition \
         --task-definition Tarefa_API-Go \
         --query taskDefinition > task-definition.json
