name: Entrega continua

on:
  workflow_call:
  
jobs:

  Deploy_ECS:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
