name: Deploy EKS

on:
  workflow_call:
  
jobs:

  EKS:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: git clone https://github.com/matheusrmello/infra_CI_K8S.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - run: terraform -chdir=infra_CI_K8S/env/Homolog init
    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog destroy -auto-approve
    - run: return 1

    - run: echo "$(terraform -chdir=infra_CI_K8S/env/Homolog output -raw IP_db)" 
      id: URL

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0

    - run: aws sts get-caller-identity
    - run: aws eks update-kubeconfig --region us-east-1 --name homolog2
    - run: kubectl get svc

   
    - run: kubectl delete secret dbhost --ignore-not-found
    - run: kubectl create secret generic dbhost --from-literal=HOST=${{ steps.URL.outputs.stdout }}
    
    - run: kubectl delete secret dbport --ignore-not-found
    - run: kubectl create secret generic dbport --from-literal=DBPORT=${{ secrets.DBPORT }}
    
    - run: kubectl delete secret dbuser --ignore-not-found
    - run: kubectl create secret generic dbuser --from-literal=USER=${{ secrets.DBUSER }}
    
    - run: kubectl delete secret dbpassword --ignore-not-found
    - run: kubectl create secret generic dbpassword --from-literal=PASSWORD=${{ secrets.DBPASSWORD }}
    
    - run: kubectl delete secret dbname --ignore-not-found
    - run: kubectl create secret generic dbname --from-literal=DBNAME=${{ secrets.DBNAME }}
    
    - run: kubectl delete secret port --ignore-not-found
    - run: kubectl create secret generic port --from-literal=PORT=8000
    
    - run: kubectl apply -f infra_CI_K8S/go.yaml

    - run: kubectl set image deployment/go-api go=matheusmello09/go_ci:v${{ github.run_number	 }}


